_wandb:
    value:
        cli_version: 0.19.2
        code_path: code/train.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
            "2":
                - 1
                - 2
                - 3
                - 55
            "3":
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 64
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
n_steps:
    value: 2048
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 1e+06
